# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnrollmentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetectionWindow(object):
    def setupUi(self, DetectionWindow):
        DetectionWindow.setObjectName("DetectionWindow")
        DetectionWindow.resize(QtCore.QSize(996, 592))
        DetectionWindow.setFixedSize(QtCore.QSize(996, 592))
        DetectionWindow.setMinimumSize(QtCore.QSize(996, 592))
        DetectionWindow.setMaximumSize(QtCore.QSize(996, 700))
        DetectionWindow.setBaseSize(QtCore.QSize(996, 592))
        DetectionWindow.setStyleSheet("QDialog {\n"
"background-color:  #2a292e;\n"
"}\n"
"\n"
"QLabel {\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton{\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"color: #1db954;\n"
"border: 2px solid #1db954;\n"
"border-radius: 14px;\n"
"letter-spacing: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"color: #121212;\n"
"background-color:     #1db954;\n"
"border: 2px solid #121212;\n"
"}\n"
"\n"
"QHBoxLayout {\n"
"border: 2px solid green;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(DetectionWindow)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 25, 25, 25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.information = QtWidgets.QHBoxLayout()
        self.information.setObjectName("information")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, 0, 10, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(DetectionWindow)
        self.label_3.setStyleSheet("color: white;\n"
"border: 2px solid #535353;\n"
"border-radius: 14px;\n"
"margin-bottom: 10px;\n"
"padding: 10px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalWidget = QtWidgets.QWidget(DetectionWindow)
        self.verticalWidget.setStyleSheet("border: 2px solid #535353;\n"
"border-radius: 14px;")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setStyleSheet("color: white;\n"
"border: 2px solid #535353;\n"
"border-radius: 14px;\n"
"padding: 10px;\n"
"margin: 10px;\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.verticalWidget)
        self.textEdit.setMinimumSize(QtCore.QSize(270, 30))
        self.textEdit.setMaximumSize(QtCore.QSize(270, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setStyleSheet("color: white;\n"
"border: 2px solid #535353;\n"
"border-radius: 14px;\n"
"padding: 10px;\n"
"margin: 10px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalWidget)
        self.textEdit_2.setMinimumSize(QtCore.QSize(270, 35))
        self.textEdit_2.setMaximumSize(QtCore.QSize(270, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.label_4 = QtWidgets.QLabel(self.verticalWidget)
        self.label_4.setStyleSheet("color: white;\n"
"border: 2px solid #535353;\n"
"border-radius: 14px;\n"
"padding: 10px;\n"
"margin: 10px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit_3 = QtWidgets.QTextEdit(self.verticalWidget)
        self.textEdit_3.setMinimumSize(QtCore.QSize(270, 35))
        self.textEdit_3.setMaximumSize(QtCore.QSize(270, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout.addWidget(self.textEdit_3)
        self.verticalLayout_4.addWidget(self.verticalWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.information.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.information)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.detection_camera = QtWidgets.QLabel(DetectionWindow)
        self.detection_camera.setMinimumSize(QtCore.QSize(600, 400))
        self.detection_camera.setStyleSheet("QLabel {\n"
"border-radius: 14px;\n"
"border: 2px solid #535353;\n"
"}")
        self.detection_camera.setObjectName("detection_camera")
        self.verticalLayout_3.addWidget(self.detection_camera)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(DetectionWindow)
        self.pushButton_2.setMinimumSize(QtCore.QSize(155, 56))
        self.pushButton_2.setMaximumSize(QtCore.QSize(155, 56))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(DetectionWindow)
        self.pushButton_3.setMinimumSize(QtCore.QSize(155, 56))
        self.pushButton_3.setMaximumSize(QtCore.QSize(155, 56))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(DetectionWindow)
        QtCore.QMetaObject.connectSlotsByName(DetectionWindow)

    def retranslateUi(self, DetectionWindow):
        _translate = QtCore.QCoreApplication.translate
        DetectionWindow.setWindowTitle(_translate("DetectionWindow", "Enrollment"))
        self.label_3.setText(_translate("DetectionWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">INFORMATION</span></p></body></html>"))
        self.label.setText(_translate("DetectionWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">NAME</span></p></body></html>"))
        self.textEdit.setHtml(_translate("DetectionWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("DetectionWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">SURNAME</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("DetectionWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("DetectionWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">PLAYLIST ID</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("DetectionWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.detection_camera.setText(_translate("DetectionWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">TAKE PHOTO TO REGISTER YOUR FACE</span></p></body></html>"))
        self.pushButton_2.setText(_translate("DetectionWindow", "TAKE PHOTO"))
        self.pushButton_3.setText(_translate("DetectionWindow", "NEXT"))

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DetectionWindow = QtWidgets.QDialog()
    ui = Ui_DetectionWindow()
    ui.setupUi(DetectionWindow)
    DetectionWindow.show()
    sys.exit(app.exec_())
"""
    